name: build via meson
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ mob ]
  pull_request:
    branches: [ mob ]

jobs:
  meson:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        if [ "${{ contains(matrix.os, 'ubuntu') }}" = "true" ]; then
          sudo apt update
          sudo apt remove -y firefox
          sudo apt upgrade -y
          sudo apt install -y python3-pip python3-setuptools
          python3 -m pip install meson ninja
        else
          brew update
          brew install meson ninja
        fi

    - name: Configure and build
      run: |
        meson setup builddir
        meson compile -C builddir
